Repository openmessaging/openmessaging-storage-dledger, pull requests merged in 2020-03, with the labels that each got.

#49 Change a way to calculate quorumIndex
  src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
Labels: enhancement

#50 [ISSUE RocketMQ#1778]
  src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
  src/main/java/io/openmessaging/storage/dledger/protocol/DLedgerResponseCode.java
  src/main/java/io/openmessaging/storage/dledger/store/file/DLedgerMmapFileStore.java
  src/test/java/io/openmessaging/storage/dledger/store/DLedgerMappedFileStoreTest.java
Labels: bug

#53 [ISSUE #52] make ledgerEndTerm be equals with logs term if it is not leader
  src/main/java/io/openmessaging/storage/dledger/store/DLedgerMemoryStore.java
  src/main/java/io/openmessaging/storage/dledger/store/file/DLedgerMmapFileStore.java
Labels: bug, enhancement
